services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pomodoro

  cache:
    image: redis:8.2.1-alpine
    ports:
      - '6379:6379'
